### ISSUE TITLE
using qa_is_mobile_probably()

### ISSUE THREAD

**Issue by stevenev** [sama55/q2a-caching#22]
System is either using regular or mobile theme.  Adding qa_is_mobile_probably() is extra logic, and IMO not needed, and in fact could cause logical error.

**Comment by sama55** [comment]
I want a little more detail (What is logical error?).
My recognition:
Theme is distributed by this function. Cache also needs to be prepared two ways (for PC and for mobile).

**Comment by stevenev** [comment]
Yes, true, cache needs to be prepared for mobile/desktop.  Just saying that the "probably" logic is already in:

function qa_get_site_theme()
it returns:  return qa_opt(qa_is_mobile_probably() ? 'site_theme_mobile' : 'site_theme');

So suggest removing it from below (double selection, serves no purpose?):

if(!qa_is_mobile_probably() || qa_opt('site_theme') == qa_opt('site_theme_mobile')) {

Write:
if( qa_opt('site_theme') == qa_opt('site_theme_mobile')) {

**Comment by sama55** [comment]
Sorry, I can not understand well. I tested this part many times, but I do not find particularly problem. Did you detect a specific problem?

**Comment by stevenev** [comment]
Mobile vs. desktop has bee decided in  qa_get_site_theme() already.

The point is why qa_is_mobile_probably() is being used in cache code, when that decision was already made about mobile vs desktop.

Hope that is easier to understand.

**Comment by stevenev** [comment]
Please feel free to ignore this and close.  It is not a show stopper.  It is just extra logic (to me).

**Comment by sama55** [comment]
I understood. qa_get_site_theme() returns "value" of theme options (e.g. Classic, Candy, Snow, etc).

**Comment by stevenev** [comment]
Ok, you are right, my bad.

I think the bold part is not correct:

if(!qa_is_mobile_probably() || **qa_opt('site_theme') == qa_opt('site_theme_mobile'**)) {

why? because if the two themes are equal, then mobile version is never saved.  But each theme can has logic that puts out extra code in case of mobile (using 'probably').  So there is a clash.

The bold needs to be eliminated IMO.

**Comment by sama55** [comment]
This line is there was a little mistake. The judgment order is reversed. Although not say in a loud voice, I have little doubt qa_is_mobile_probably. Function name is "probably" (^_^;;). I changed code.
if(qa_opt('site_theme') == qa_opt('site_theme_mobile') || !qa_is_mobile_probably()) {

**Comment by sama55** [comment]
In addition, in case of only qa_is_mobile_probably(), The amount of cash will increase. Worst, it will be doubled. In particular, mobile cache is not required at responsive theme site.

**Comment by sama55** [comment]
It was solved.

**Comment by stevenev** [comment]
Have to cache both mobile and desktop. That is the only option. Why because, 'probably' puts out extra html tags for some of the themes.  So the html is NOT the same.

This is still not right in the commit:
if(qa_opt('site_theme') == qa_opt('site_theme_mobile') || !qa_is_mobile_probably()) {

Should be:
**if( !qa_is_mobile_probably()) {**

This is serious bug.

**Comment by sama55** [comment]
Rather than think in your head, please try to actually test. So, you may find the meaning of this code.

**Comment by stevenev** [comment]
I think no need to discuss this a lot.

If you look at snowflat theme, you will find:

// sidebar styles for desktop (must use server-side UA detection, not media queries)
		if (!qa_is_mobile_probably()) {
			$css[] = '.qa-sidepanel { width: 25%; padding: 0px; float: right; overflow: hidden; *zoom: 1; }';
		}

which means it outputs different things for mobile, so cannot keep a single version for both desktop and mobile.

**Comment by sama55** [comment]
You are misunderstanding a little about option of dividing standard theme and mobile theme.
SnowFlat is so called "responsive" theme that has been made on the assumption that users set same theme to both (desktop and mobile). However, in some cases Q2A users set different themes to the desktop and mobile.

I say again. Please test without thinking in your head.
Pattern that you should test:
Desktop = Snow
Mobile = SnowFlat
Of course, please visit the SnowFlat by mobile device.

**Comment by stevenev** [comment]
In Pattern-B (that is the one I have problem with):

As you say only ONE file is saved.

But when you visit, it uses this code:
if (!qa_is_mobile_probably()) {
$css[] = '.qa-sidepanel { width: 25%; padding: 0px; float: right; overflow: hidden; *zoom: 1; }';
}

So depending on 'samsung', it would add extra css....  desktop, no extra css.

I must be very confused.
